#pragma once

//For use by Pika applications
#include "Pika/Core/Base.h"
#include "Pika/Core/Log.h"
#include "Pika/Core/Application.h"
#include "Pika/Core/Layer.h"
#include "Pika/ImGui/ImGuiLayer.h"
#include "Pika/Core/Input.h"
#include "Pika/Core/Timer.h"
#include "Pika/Core/Timestep.h"
#include "Pika/Core/Random.h"
#include "Pika/Core/Shortcut.h"
#include "Pika/Core/UUID.h"
#include "Pika/Debug/Instrumentor.h"
//-----------------Render----------------
#include "Pika/Renderer/RenderCommand.h"
#include "Pika/Renderer/Renderer2D.h"
#include "Pika/Renderer/Renderer3D.h"
#include "Pika/Renderer/VertexArray.h"
#include "Pika/Renderer/Buffer.h"
#include "Pika/Renderer/Shader.h"
#include "Pika/Renderer/RendererAPI.h"
#include "Pika/Renderer/GraphicsContext.h"
#include "Pika/Renderer/Texture.h"
#include "Pika/Renderer/SubTexture2D.h"
#include "Pika/Renderer/Framebuffer.h"
#include "Pika/Renderer/Camera.h"
#include "Pika/Renderer/Camera2D.h"
#include "Pika/Renderer/Camera2DController.h"
#include "Pika/Renderer/EditorCamera.h"
//-----------------Scene-----------------
#include "Pika/Scene/Scene.h"
#include "Pika/Scene/Entity.h"
#include "Pika/Scene/Components.h"
#include "Pika/Scene/SceneCamera.h"
#include "Pika/Scene/SceneSerializer.h"
#include "Pika/Scene/SceneRenderer.h"